### ISSUE TITLE
Feature: Add SCTE-35 insert messages

### ISSUE THREAD

**Issue by wyatt-vaughan** [bitfocus/companion-module-aws-elementallive#12]
Hello, I already use this module for starting and stopping live streams but I have to use an HTTP POST request to add SCTE 35 insert messages during live football games. 

I have already made a fork and implemented it on my local companion. 

What should my next step be?

**Comment by bryce-seifert** [comment]
Closed via https://github.com/bitfocus/companion-module-aws-elementallive/pull/13
