### ISSUE TITLE
Event Status Feedback Not Returning

### ISSUE THREAD

**Issue by claymcneill** [bitfocus/companion-module-aws-elementallive#4]
Actions for Start, Stop, Reset working as expected for Elemental Live event 1. When adding Feedback for the same event, the background color never changes based on status. 

Noting the following in Debug for Module - 
debug: TypeError: Cannot read properties of undefined (reading 'replace')

I've checked in Postman for event status - http://{hostname}/api/live_events/1/status and it's returning data.

**Comment by claymcneill** [comment]
Also noting the System variables are shown as undefined.

**Comment by bryce-seifert** [comment]
Looks like it should be fixed in module version 1.1.0 via https://github.com/bitfocus/companion-module-aws-elementallive/pull/13
